# Generated by Django 5.2.4 on 2025-08-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchs', '0002_alter_product_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=20),
        ),
    ]
