# Generated by Django 5.2.4 on 2025-08-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchs', '0003_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
