# Generated by Django 5.2.4 on 2025-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchs', '0004_remove_product_payment_type_remove_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
